### ISSUE TITLE
Trouble running tests

### ISSUE THREAD

**Issue by chris** [brightcove-archive/ooyala_retries#5]
We're having trouble getting the tests to run. Using Ruby 1.9.3. We see:

```
# bundle exec rake test
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/scope-0.2.3/lib/scope.rb:1:in `require'
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/scope-0.2.3/lib/scope.rb:1:in `<top (required)>'
  /Users/chris/Code/HT/retries/test/retries_test.rb:1:in `require'
  /Users/chris/Code/HT/retries/test/retries_test.rb:1:in `<top (required)>'
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
  /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/scope-0.2.3/lib/scope.rb:6:in `<module:Scope>'
--------------------------------------------------------------------------------
RR deprecation warning: RR now has an autohook system. You don't need to
`include RR::Adapters::*` in your test framework's base class anymore.
--------------------------------------------------------------------------------

MiniTest::Unit::TestCase is now Minitest::Test. From /Users/chris/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/scope-0.2.3/lib/scope.rb:12:in `inherited'
Run options: --seed 21771

# Running:



Finished in 0.001397s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

Just wondering if we're missing anything, or if you have any ideas? I'm guessing it's some of these warnings and such that are causing some kind of conflict.

p.s. I'd like to get these working to be able to send a PR for this:
https://github.com/hoteltonight/retries/pull/1

**Comment by cespare** [comment]
Thanks, fixed.

**Comment by chris** [comment]
Thanks @cespare for fixing so quickly - all tests run for me.
